[package]
name = "msm_graph"
version = "0.1.0"
authors = ["Arkadiusz Piekarz <piekarzarkadiusz@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.5.4"

[dev-dependencies]
assert_cmd = { version = "1.0.7", default-features = false }
tempfile = { version = "3.2.0", default-features = false }
