[package]
name = "boost-msm-grapher"
version = "0.1.0"
authors = ["Arkadiusz Piekarz <piekarzarkadiusz@gmail.com>"]
edition = "2021"

[dependencies]
regex = "1.5.4"

[dev-dependencies]
assert_cmd = { version = "2.0.2", default-features = false }
tempfile = { version = "3.2.0", default-features = false }
